
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: error
  logs:
    custom_components.multizone_heating: debug
    custom_components.trvswitch: debug

multizone_heating:
  enabled: True
  pumps:
    - entity_id: switch.mainheater
  zones:
    - name: "Zone TF"
      away_temp: 16
      pumps:
        - entity_id: switch.pumptf
          keep_active: 45
      subzones:
        - name: AA
          sensor: input_number.aa_temp
          valves:
            - switch: switch.trv_aa_1
            - switch: switch.trv_aa_2
          control: climate.test_thermostat
        - name: David
          sensor: input_number.david_temp
          valves:
            - switch: switch.trv_david_1
          control: climate.david
          active_temp: 24.5
    - name: "zone MF"
      pumps:
        - entity_id: switch.pumpmf
          keep_alive: 5
      subzones:
        - name: Kitchen
          sensor: input_number.kitchen_temp
          control: climate.kitchen

input_boolean:
  mainheater:
    name: Main heater
  pumpmf:
    name: Pump for middle floor
  pumptf:
    name: Pump for top floor

switch:
  - platform: trvswitch
    climate: climate.trv_aa_1
    name: TRV AA 1
  - platform: trvswitch
    climate: climate.trv_aa_2
    name: TRV AA 2
  - platform: trvswitch
    climate: climate.trv_david_1
    name: TRV David 1
  - platform: trvswitch
    climate: climate.trv_david_2
    name: TRV David 2
  - platform: trvswitch
    climate: climate.trv_kitchen
    name: TRV Kitchen

  - platform: template
    switches:
      mainheater:
        friendly_name: Main heater
        value_template: "{{ is_state('input_boolean.mainheater','on') }}"
        turn_on:
          service: input_boolean.turn_on
          data:
            entity_id: input_boolean.mainheater
        turn_off:
          service: input_boolean.turn_off
          data:
            entity_id: input_boolean.mainheater
      pumpmf:
        friendly_name: Pump MF
        value_template: "{{ is_state('input_boolean.pumpmf','on') }}"
        turn_on:
          service: input_boolean.turn_on
          data:
            entity_id: input_boolean.pumpmf
        turn_off:
          service: input_boolean.turn_off
          data:
            entity_id: input_boolean.pumpmf
      pumptf:
        friendly_name: Pump TF
        value_template: "{{ is_state('input_boolean.pumptf','on') }}"
        turn_on:
          service: input_boolean.turn_on
          data:
            entity_id: input_boolean.pumptf
        turn_off:
          service: input_boolean.turn_off
          data:
            entity_id: input_boolean.pumptf

climate:
  - platform: generic_thermostat
    name: David
    heater: switch.zone_tf_david
    target_sensor: input_number.david_temp

  - platform: generic_thermostat
    name: Kitchen
    heater: switch.zone_mf_kitchen
    target_sensor: input_number.kitchen_temp

  - platform: generic_thermostat
    name: AA
    heater: switch.zone_tf_aa
    target_sensor: input_number.aa_temp

  - platform: smart_thermostat    
    name: AA
    unique_id: st_test_thermostat
    target_sensor: input_number.aa_temp
    precision: 0.1    
    heater:
#      - entity_id: input_number.target_temp
#        switch_entity_id: switch.subzone_aa
      - entity_id: climate.aa
        pid_sample_period: 30
        pid_params: 1.3, 0.5, 0.2

  - platform: generic_thermostat
    name: TRV AA 1
    heater: switch.dummy
    target_sensor: input_number.david_temp
  - platform: generic_thermostat
    name: TRV AA 2
    heater: switch.dummy
    target_sensor: input_number.david_temp
  - platform: generic_thermostat
    name: TRV David 1
    heater: switch.dummy
    target_sensor: input_number.david_temp
  - platform: generic_thermostat
    name: TRV David 2
    heater: switch.dummy
    target_sensor: input_number.david_temp
  - platform: generic_thermostat
    name: TRV Kitchen
    heater: switch.dummy
    target_sensor: input_number.david_temp
